/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2023. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class WorkoutRecord {
    uid: string = "";
    recordId: number;
    workoutType: string;
    totalTime: number;
    averageSpeed: number;
    createTime: Date;
    snapshotUrl: string;
    totalDistance: number;

    constructor() {
    }

    getFieldTypeMap():  Map<string, string> {
        let fieldTypeMap = new Map<string, string>();
        fieldTypeMap.set('uid', 'String');
        fieldTypeMap.set('recordId', 'LongAutoIncrement');
        fieldTypeMap.set('workoutType', 'String');
        fieldTypeMap.set('totalTime', 'Integer');
        fieldTypeMap.set('averageSpeed', 'Float');
        fieldTypeMap.set('createTime', 'Date');
        fieldTypeMap.set('snapshotUrl', 'String');
        fieldTypeMap.set('totalDistance', 'Float');
        return fieldTypeMap;
    }

    getClassName(): string {
        return 'WorkoutRecord';
    }

    getPrimaryKeyList(): string[] {
        let primaryKeyList: string[] = [];
        primaryKeyList.push('recordId');
        return primaryKeyList;
    }

    getIndexList(): string[] {
        let indexList: string[] = [];
        return indexList;
    }

    getEncryptedFieldList(): string[] {
        let encryptedFieldList: string[] = [];
        return encryptedFieldList;
    }

    setUid(uid: string): void {
        this.uid = uid;
    }

    getUid(): string  {
        return this.uid;
    }

    setRecordId(recordId: number): void {
        this.recordId = recordId;
    }

    getRecordId(): number  {
        return this.recordId;
    }

    setWorkoutType(workoutType: string): void {
        this.workoutType = workoutType;
    }

    getWorkoutType(): string  {
        return this.workoutType;
    }

    setTotalTime(totalTime: number): void {
        this.totalTime = totalTime;
    }

    getTotalTime(): number  {
        return this.totalTime;
    }

    setAverageSpeed(averageSpeed: number): void {
        this.averageSpeed = averageSpeed;
    }

    getAverageSpeed(): number  {
        return this.averageSpeed;
    }

    setCreateTime(createTime: Date): void {
        this.createTime = createTime;
    }

    getCreateTime(): Date  {
        return this.createTime;
    }

    setSnapshotUrl(snapshotUrl: string): void {
        this.snapshotUrl = snapshotUrl;
    }

    getSnapshotUrl(): string  {
        return this.snapshotUrl;
    }

    setTotalDistance(totalDistance: number): void {
        this.totalDistance = totalDistance;
    }

    getTotalDistance(): number  {
        return this.totalDistance;
    }

    static parseFrom(inputObject: any): WorkoutRecord {
        let result = new WorkoutRecord();
        if (!inputObject) {
            return result;
        }
        if (inputObject.uid) {
            result.uid = inputObject.uid;
        }
        if (inputObject.recordId) {
            result.recordId = inputObject.recordId;
        }
        if (inputObject.workoutType) {
            result.workoutType = inputObject.workoutType;
        }
        if (inputObject.totalTime) {
            result.totalTime = inputObject.totalTime;
        }
        if (inputObject.averageSpeed) {
            result.averageSpeed = inputObject.averageSpeed;
        }
        if (inputObject.createTime) {
            result.createTime = new Date(inputObject.createTime);
        }
        if (inputObject.snapshotUrl) {
            result.snapshotUrl = inputObject.snapshotUrl;
        }
        if (inputObject.totalDistance) {
            result.totalDistance = inputObject.totalDistance;
        }
        return result;
    }
}

export { WorkoutRecord };