/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2023. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class UserInfo {
    uid: string;
    phoneNumber: string = "";
    nickname: string;
    avatarUrl: string;
    createTime: Date;
    updateTime: Date;

    constructor() {
    }

    getFieldTypeMap():  Map<string, string> {
        let fieldTypeMap = new Map<string, string>();
        fieldTypeMap.set('uid', 'String');
        fieldTypeMap.set('phoneNumber', 'String');
        fieldTypeMap.set('nickname', 'String');
        fieldTypeMap.set('avatarUrl', 'String');
        fieldTypeMap.set('createTime', 'Date');
        fieldTypeMap.set('updateTime', 'Date');
        return fieldTypeMap;
    }

    getClassName(): string {
        return 'UserInfo';
    }

    getPrimaryKeyList(): string[] {
        let primaryKeyList: string[] = [];
        primaryKeyList.push('uid');
        return primaryKeyList;
    }

    getIndexList(): string[] {
        let indexList: string[] = [];
        return indexList;
    }

    getEncryptedFieldList(): string[] {
        let encryptedFieldList: string[] = [];
        return encryptedFieldList;
    }

    setUid(uid: string): void {
        this.uid = uid;
    }

    getUid(): string  {
        return this.uid;
    }

    setPhoneNumber(phoneNumber: string): void {
        this.phoneNumber = phoneNumber;
    }

    getPhoneNumber(): string  {
        return this.phoneNumber;
    }

    setNickname(nickname: string): void {
        this.nickname = nickname;
    }

    getNickname(): string  {
        return this.nickname;
    }

    setAvatarUrl(avatarUrl: string): void {
        this.avatarUrl = avatarUrl;
    }

    getAvatarUrl(): string  {
        return this.avatarUrl;
    }

    setCreateTime(createTime: Date): void {
        this.createTime = createTime;
    }

    getCreateTime(): Date  {
        return this.createTime;
    }

    setUpdateTime(updateTime: Date): void {
        this.updateTime = updateTime;
    }

    getUpdateTime(): Date  {
        return this.updateTime;
    }

    static parseFrom(inputObject: any): UserInfo {
        let result = new UserInfo();
        if (!inputObject) {
            return result;
        }
        if (inputObject.uid) {
            result.uid = inputObject.uid;
        }
        if (inputObject.phoneNumber) {
            result.phoneNumber = inputObject.phoneNumber;
        }
        if (inputObject.nickname) {
            result.nickname = inputObject.nickname;
        }
        if (inputObject.avatarUrl) {
            result.avatarUrl = inputObject.avatarUrl;
        }
        if (inputObject.createTime) {
            result.createTime = new Date(inputObject.createTime);
        }
        if (inputObject.updateTime) {
            result.updateTime = new Date(inputObject.updateTime);
        }
        return result;
    }
}

export { UserInfo };